### ISSUE TITLE
First Landing - error of interpretation - section 01

### ISSUE THREAD

**Issue by haileypopma** [GrantMatejka/CSC-308-Travel#1]
- Remove the foreign letters(attached) and replace with application name
- simplify logo (if we keep it)

<img width="48" alt="Screen Shot 2020-02-05 at 11 33 13 AM" src="https://user-images.githubusercontent.com/60552863/73876241-874c8300-480b-11ea-8954-5cf7e5a5819f.png">

**Comment by GrantMatejka** [comment]
The logo is currently a placeholder
